export const LeveledCurriculum = [
  {
    id: 1,
    title: "Basic Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b895e541a832674533c18?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Gain confidence speaking about familiar topics",
    level: "Beginner",
    length: "10 lessons",
    why: "문법과 어휘를 얼마나 배웠든 외국인과 말하는 것은 겁이 날 수 있습니다. 영어에 대한 기본 지식은 있지만, 영어로 말할 기회가 없었다면 이 코스틀 통해 첫 영어 대화를 쉽게 시작할 수 있습니다.",
    what: "이 코스는 CEFR A2 레벨의 어휘를 다룹니다. 다양한 공통, 일상 주제에 대해 말하는 학습 중에 자신감을 얻게 됩니다. 또한, 강사가 정답을 알려주고 실수를 짚어주면서 절대적인 문법 지식을 얻게 됩니다.",
    pre: "자신에 대한 소개와 어디에서 왔는지를 말할 수 있게 됩니다. 아직 기본적인 소개에 익숙하지 않은 경우, '영어 대화 101' 코스로 시작하세요.",
    lessonPlan: [
      "Foods You Love",
      "Your Job",
      "Playing and Watching Sports",
      "The Best Pet",
      "Having Fun in Your Free Time",
      "Your Daily Routine",
      "Childhood Memories",
      "Your Family Members",
      "Your Hometown",
      "Shopping Habits",
    ],
  },
  {
    id: 2,
    title: "Intermediate Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b99d0c4288f294426b643?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Express your ideas and opinions",
    level: "Intermediate",
    length: "10 lessons",
    why: "다양한 레슨 주제를 찾고 계신가요? 이 관련성이 높은 주제 세트로 영어 토론에 빠져보세요.",
    what: "이 코스는 CEFR B1-B2 레벨의 어휘를 다룹니다. 다양한 주제를 토론하여 유창성과 이해력을 증진하게 됩니다. 또한, 문법 정확성을 높이는 데 도움이 될 원어민의 수정도 받게 됩니다.",
    pre: "이 코스를 시작하기 전에 영어 대화를 할 수 있어야 합니다.",
    lessonPlan: [
      "Cooking",
      "Your Dream Job",
      "Sports Fitness",
      "Service Animals",
      "Social Activities",
      "Your Ideal Day",
      "Childhood Friendships",
      "The Importance of Family",
      "City Life",
      "Online Shopping",
    ],
  },
  {
    id: 3,
    title: "Advanced Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b99e60b114e9a327ceb66?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Explore complex topics relevant to modern life",
    level: "Advanced",
    length: "10 lessons",
    why: "새로운 주제에 도전하여 어휘를 확장하고 영어에 대한 편안함을 늘리세요.",
    what: "이 코스는 CEFR C1-C2 레벨의 어휘를 다룹니다. 다양한 주제에 대해 길게 말해서 유창성을 얻게 됩니다. 또한, 일관성과 문법 정확성 증진에 도움을 주는 원어민의 수정을 받게 됩니다.",
    pre: "이 코스를 시작하기 전에 추상적인 주제에 대해 길게 말할 수 있어야 합니다.",
    lessonPlan: [
      "Food for Thought",
      "Developing Your Career",
      "Sports Fanaticism",
      "Exotic Pets",
      "Work-Life Balance",
      "Living Your Best Life",
      "Raising Children",
      "Family Dynamics",
      "Community Service",
      "Consumerism",
    ],
  },
  {
    id: 4,
    title: "English Conversation 101",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e7e51cca52da4ab4bd958e6?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Approachable lessons for absolute beginners",
    level: "Beginner",
    length: "10 lessons",
    why: "원어민과 영어를 말할 준비가 되지 않은 것 같아서 걱정되시나요? 두려움에서 벗어나는 데 필요한 모든 지도를 제공하는 이 코스를 생성했습니다. 오늘 스피킹을 시작하세요!",
    what: "자신을 소개하고 인사를 나누는 방법을 학습하면서 쉽게 시작하세요. 마지막 레슨까지 가면 Cambly에서 영어 대화를 계속해서 연습하고 증진하는 데 필요한 스킬을 얻게 됩니다.",
    pre: "영어 알파벳 소리에 익숙해야 합니다. 어휘, 문법 또는 발음 지식은 필요하지 않습니다.",
    lessonPlan: [
      "Greetings and Introductions",
      "Family",
      "Jobs",
      "Likes and dislikes",
      "Mid-course review",
      "Future Plans",
      "Last Weekend",
      "Travel Experiences",
      "Course Review",
      "Let's See What You Can Do!",
    ],
  },
  {
    id: 5,
    title: "English Conversation 102",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5fd9240c4143a75bf6c2de8b?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Even more approachable lessons for absolute beginners",
    level: "Beginner",
    length: "10 lessons",
    why: "",
    what: "영어로 간단한 대화를 할 수 있는 능력을 계속 개발하세요! 이 코스는 날씨나 취미와 같은 주제를 얘기할 때 자신감을 키울 수 있도록 신중하게 편성된 레슨으로 구성되어 있습니다. 친구들과 근황을 얘기하거나 스토리를 말하는 연습을 하게 됩니다. 이 코스는 기초 영어 대화에 자주 등장하는 주제를 다룹니다.",
    pre: "",
    lessonPlan: [
      "How Have You Been?",
      "Have You Heard?",
      "What Are Your Hobbies?",
      "What Do You Want to Learn?",
      "Mid-Course Review",
      "How's the Weather?",
      "How Are You Feeling?",
      "What Happened Next?",
      "End Course Review",
      "Free Flow Conversation",
    ],
  },
  {
    id: 6,
    title: "English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/60351f012675349765c2b4b2?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Practical English to use while traveling!",
    level: "Beginner",
    length: "15 lessons",
    why: "여행 영어를 배워 다음 여행은 더욱 쉽고 재미 있게 즐겨보세요. 영어는 전 세계 국제공항, 호텔, 심지어 비영어권 국가에서도 사용됩니다. 어디로 가시든, 이 코스를 통해 자신 있게 여행할 수 있을 거예요!",
    what: "이 코스에서는 일반적인 여행 상황에서 필요한 영어 단어와 문구를 배웁니다. 공항을 돌아다니고, 호텔 객실에 도착하고, 도움을 요청하는 연습을 할 뿐만 아니라, 여행 관련 대화에서 필요한 영어도 배우게 됩니다. 전문 튜터가 자신 있게 집을 나설 수 있도록 도와드려요!",
    pre: "",
    lessonPlan: [
      "Let's Begin the Journey!",
      "At the Airport",
      "On the Airplane",
      "At Immigration/Customs",
      "Review 1",
      "Transportation",
      "At the Hotel",
      "Eating at a Restaurant",
      "At the Supermarket",
      "Review 2",
      "Sightseeing and Shopping",
      "When You Get Sick",
      "When You Get into Trouble",
      "Weather",
      "Final Review",
    ],
  },
  {
    id: 7,
    title: "Intermediate Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/609fdd6fb95e4527664a7252?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "More practice expressing your ideas and opinions in English",
    level: "Intermediate",
    length: "10 lessons",
    why: "중급 수준의 주제를 영어로 말하는 능력을 더 개발해보세요!",
    what: "이 과정에서는 돈, 운동, 다이어트, 소셜 미디어와 같은 주제를 토론하는 연습을 합니다. 동시에 B1-B2 레벨의 어휘를 배우게 됩니다.",
    pre: "",
    lessonPlan: [
      "Famous People",
      "Your Cozy Home",
      "Money",
      "Exercise and Diet",
      "Movies, TV and Books",
      "Sense of Community and Volunteering",
      "Social Media",
      "Travel",
      "Holidays and Celebrations",
      "Language Learning",
    ],
  },
  {
    id: 8,
    title: "Basic Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/614cc34bd4b3950542fec97f?h=3c3c1cbf5bc5272468f8f792e0fdca7a",
    desc: "Build your fluency and confidence with conversation practice about everyday topics!",
    level: "Beginner",
    length: "10 lessons",
    why: "외국어로 말하는 것은 어렵습니다! 연습이 필요하죠. 실제 같은 상황에서 몰입도 높은 대화 주제로 튜터와 말하는 연습을 해서 능숙도를 높이세요. 영어 기본 문법과 어휘에 이미 익숙할지라도, 이 과정의 체계적인 수업을 통해 자신감과 말하기 능력을 키울 수 있습니다.",
    what: "이 과정은 CEFR A2-B1 레벨의 어휘를 다룹니다. 새로운 단어를 배워 말할 때 통합할 수 있는 기회가 제공됩니다. 튜터와 함께 주제를 공부하면서 A2-B1 레벨의 문법을 연습하고 정확도를 높일 수 있습니다.",
    pre: "이 과정은 '기본 대화 주제 파트 1'과 이어집니다. 그 과정을 수강했다면, 이미 준비가 되신 겁니다! 수강하지 않으셨다면, 본인에 대한 기본적인 정보와 간단한 문장을 영어로 말할 수 있어야 합니다.",
    lessonPlan: [
      "Your Home",
      "House Chores",
      "Sleeping",
      "What to Eat",
      "Getting Sick",
      "Time",
      "Money",
      "Transportation",
      "Directions",
      "Your Culture",
    ],
  },
  {
    id: 9,
    title: "Intermediate English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/61df1c3c28110edf71466b41?h=e70034f26f8c7814889ea26c2db326e4",
    desc: "Practice communication skills to use for your next trip!",
    level: "Intermediate",
    length: "10 lessons",
    why: "여행 경험을 최대한 활용할 수 있도록 영어 실력을 향상하세요. 실용적인 양방향 과정을 통해 다음 여행에서 유창하고 자신 있게 말할 수 있도록 준비하세요.",
    what: "이 과정은 기본 여행 영어 이상의 말하기 능력을 향상시켜 여행을 더욱더 즐길 수 있습니다. 수업마다 멕시코로 여행하는 커플을 따라가면서, 레스토랑에서 웨이터에게 질문하고 다른 여행객과 담소를 나누는 등 일반적인 여행 상황을 다룹니다. 다음 모험을 철저하게 준비할 수 있도록, 어휘와 문법뿐만 아니라 발음과 다른 말하기 능력을 연습합니다.",
    pre: "",
    lessonPlan: [
      "Taking a Trip",
      "Finding a Place to Stay",
      "Preparing for a Trip",
      "Traveling by Plane",
      "Renting a Car",
      "Going on an Excursion",
      "Sightseeing",
      "Eating at a Restaurant",
      "Meeting People",
      "Talking About the Trip",
    ],
  },
  {
    id: 10,
    title: "Basic English for Daily Life",
    src: "https://camblycurriculumicons.s3.amazonaws.com/62ec1e1a3d180c617e5d387e?h=479b1055b1e0316ecbe77dc4473386aa",
    desc: "Everyday vocabulary and basic grammar for English beginners",
    level: "Beginner",
    length: "15 lessons",
    why: "아주 기본적인 영어 문법을 배우거나 연습해야 한다면, 이 코스를 수강해보세요!",
    what: "이 코스에서는 전문 튜터가 영어 문법을 마스터할 수 있도록 도와줍니다. 동사 'to be' 활용, 영어 대명사 사용, 간단한 질문을 하는 규칙과 함께 기타 기초 문법을 배우게 됩니다. 또한, 숫자, 시간, 가족, 음식과 같은 주제와 관련하여 매일 사용하는 어휘를 연습합니다.",
    pre: "영어 알파벳 소리에 익숙해야 합니다. 어휘, 문법 또는 발음 지식은 필요하지 않습니다.",
    lessonPlan: [
      "Nice to meet you.",
      "This is my dog.",
      "Do you like pizza?",
      "Do you play any sports?",
      "Review (1)",
      "We cook together.",
      "There are some spring rolls.",
      "This is my family.",
      "Who is this?",
      "Review (2)",
      "What time do you get up?",
      "How do you get to the station?",
      "How do we get there?",
      "Could I try this on?",
      "Review (3)",
    ],
  },
  {
    id: 11,
    title: "Advanced Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/63221f91b96e4cae6974ed2f?h=7fb71ce7a9840a0376531867eba5478e",
    desc: "Express your opinions on complex topics while fine-tuning your English!",
    level: "Advanced",
    length: "8 lessons",
    why: "이 코스는 영어 대화 능력을 다듬으면서 어휘를 늘리는 데 도움이 됩니다.",
    what: "이 코스에서는 SNS에 대한 찬반 논쟁, 지루함의 좋은 점, 음식 트렌드 등과 같이 복잡한 주제에 관해 자신의 의견과 아이디어를 표현합니다. 또한, 논쟁이나 데이터에 대응하는 연습을 하고, 세심하게 추가 질문을 함으로써 좀 더 길고 몰입도 높은 대화를 하게 됩니다. 이 코스에서 다루는 어휘는 C1-C2 레벨입니다.",
    pre: "이 코스를 시작하기 전에 추상적인 주제에 대해 길게 말할 수 있어야 합니다.",
    lessonPlan: [
      "Online Education",
      "Hobbies & Free Time",
      "Stages of Life",
      "Success and Failure",
      "Travel",
      "Social Media & Networking",
      "Farm to Fork",
      "The Environment",
    ],
  },
  {
    id: 12,
    title: "Advanced English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/6323945a1cd02f2fb42bb6b6?h=3a87b8c2f645714b6225f92dd79f08b0",
    desc: "Master the language you need for international travel!",
    level: "Advanced",
    length: "10 lessons",
    why: "이 코스는 사람들이 해외여행을 할 때 자주 마주치는 복잡한 상황을 집중적으로 다룹니다. 출장이든 개인 여행이든, 모든 상황에 대비할 수 있어요!",
    what: "이 코스에서는 출장을 계획해서 떠나는 여자 사업가를 따라가게 됩니다. 비행기 좌석 업그레이드, 여행 시 필요한 서류, 음식점에서 식이 제한 사항을 말하는 것 등 다양한 주제를 가지고 폭넓게 듣기 및 말하기 연습을 합니다. 또한, 회사 동료나 여행객과 관계를 쌓기 위해 다양한 여행 경험을 얘기하는 연습도 합니다. 이 코스에는 여행객을 대상으로 한 팟캐스트와 후기를 들을 때 필요한 영어 기술이 포함되어 있습니다. 따라서 다음번 여행에서는 현지인과 전 세계의 관광객이 추천하는 최고의 음식점과 호텔을 찾을 수 있습니다!",
    pre: "",
    lessonPlan: [
      "Preparing for a Trip",
      "Documents and Transportation",
      "Departing on a Trip",
      "Arriving at the Destination",
      "Staying in a Hotel",
      "Meeting Others",
      "Eating at Restaurants",
      "Getting Sick",
      "Sightseeing and Shopping",
      "Coming Back from a Trip",
    ],
  },
];
