export const LeveledCurriculum = [
  {
    id: 1,
    title: "Basic Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b895e541a832674533c18?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Gain confidence speaking about familiar topics",
    level: "Beginner",
    length: "10 lessons",
    why: "문법과 어휘를 얼마나 배웠든 외국인과 말하는 것은 겁이 날 수 있습니다. 영어에 대한 기본 지식은 있지만, 영어로 말할 기회가 없었다면 이 코스틀 통해 첫 영어 대화를 쉽게 시작할 수 있습니다.",
    what: "이 코스는 CEFR A2 레벨의 어휘를 다룹니다. 다양한 공통, 일상 주제에 대해 말하는 학습 중에 자신감을 얻게 됩니다. 또한, 강사가 정답을 알려주고 실수를 짚어주면서 절대적인 문법 지식을 얻게 됩니다.",
    pre: "자신에 대한 소개와 어디에서 왔는지를 말할 수 있게 됩니다. 아직 기본적인 소개에 익숙하지 않은 경우, '영어 대화 101' 코스로 시작하세요.",
    lessonPlan: [
      "Foods You Love",
      "Your Job",
      "Playing and Watching Sports",
      "The Best Pet",
      "Having Fun in Your Free Time",
      "Your Daily Routine",
      "Childhood Memories",
      "Your Family Members",
      "Your Hometown",
      "Shopping Habits",
    ],
  },
  {
    id: 2,
    title: "Intermediate Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b99d0c4288f294426b643?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Express your ideas and opinions",
    level: "Intermediate",
    length: "10 lessons",
    why: "다양한 레슨 주제를 찾고 계신가요? 이 관련성이 높은 주제 세트로 영어 토론에 빠져보세요.",
    what: "이 코스는 CEFR B1-B2 레벨의 어휘를 다룹니다. 다양한 주제를 토론하여 유창성과 이해력을 증진하게 됩니다. 또한, 문법 정확성을 높이는 데 도움이 될 원어민의 수정도 받게 됩니다.",
    pre: "이 코스를 시작하기 전에 영어 대화를 할 수 있어야 합니다.",
    lessonPlan: [
      "Cooking",
      "Your Dream Job",
      "Sports Fitness",
      "Service Animals",
      "Social Activities",
      "Your Ideal Day",
      "Childhood Friendships",
      "The Importance of Family",
      "City Life",
      "Online Shopping",
    ],
  },
  {
    id: 3,
    title: "Advanced Conversation Topics",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e2b99e60b114e9a327ceb66?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Explore complex topics relevant to modern life",
    level: "Advanced",
    length: "10 lessons",
    why: "새로운 주제에 도전하여 어휘를 확장하고 영어에 대한 편안함을 늘리세요.",
    what: "이 코스는 CEFR C1-C2 레벨의 어휘를 다룹니다. 다양한 주제에 대해 길게 말해서 유창성을 얻게 됩니다. 또한, 일관성과 문법 정확성 증진에 도움을 주는 원어민의 수정을 받게 됩니다.",
    pre: "이 코스를 시작하기 전에 추상적인 주제에 대해 길게 말할 수 있어야 합니다.",
    lessonPlan: [
      "Food for Thought",
      "Developing Your Career",
      "Sports Fanaticism",
      "Exotic Pets",
      "Work-Life Balance",
      "Living Your Best Life",
      "Raising Children",
      "Family Dynamics",
      "Community Service",
      "Consumerism",
    ],
  },
  {
    id: 4,
    title: "English Conversation 101",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5e7e51cca52da4ab4bd958e6?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Approachable lessons for absolute beginners",
    level: "Beginner",
    length: "10 lessons",
  },
  {
    id: 5,
    title: "English Conversation 102",
    src: "https://camblycurriculumicons.s3.amazonaws.com/5fd9240c4143a75bf6c2de8b?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Even more approachable lessons for absolute beginners",
    level: "Beginner",
    length: "10 lessons",
  },
  {
    id: 6,
    title: "English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/60351f012675349765c2b4b2?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "Practical English to use while traveling!",
    level: "Beginner",
    length: "15 lessons",
  },
  {
    id: 7,
    title: "Intermediate Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/609fdd6fb95e4527664a7252?h=d41d8cd98f00b204e9800998ecf8427e",
    desc: "More practice expressing your ideas and opinions in English",
    level: "Intermediate",
    length: "10 lessons",
  },
  {
    id: 8,
    title: "Basic Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/614cc34bd4b3950542fec97f?h=3c3c1cbf5bc5272468f8f792e0fdca7a",
    desc: "Build your fluency and confidence with conversation practice about everyday topics!",
    level: "Beginner",
    length: "10 lessons",
  },
  {
    id: 9,
    title: "Intermediate English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/61df1c3c28110edf71466b41?h=e70034f26f8c7814889ea26c2db326e4",
    desc: "Practice communication skills to use for your next trip!",
    level: "Intermediate",
    length: "10 lessons",
  },
  {
    id: 10,
    title: "Basic English for Daily Life",
    src: "https://camblycurriculumicons.s3.amazonaws.com/62ec1e1a3d180c617e5d387e?h=479b1055b1e0316ecbe77dc4473386aa",
    desc: "Everyday vocabulary and basic grammar for English beginners",
    level: "Beginner",
    length: "15 lessons",
  },
  {
    id: 11,
    title: "Advanced Conversation Topics Part 2",
    src: "https://camblycurriculumicons.s3.amazonaws.com/63221f91b96e4cae6974ed2f?h=7fb71ce7a9840a0376531867eba5478e",
    desc: "Express your opinions on complex topics while fine-tuning your English!",
    level: "Advanced",
    length: "8 lessons",
  },
  {
    id: 12,
    title: "Advanced English for Travel",
    src: "https://camblycurriculumicons.s3.amazonaws.com/6323945a1cd02f2fb42bb6b6?h=3a87b8c2f645714b6225f92dd79f08b0",
    desc: "Master the language you need for international travel!",
    level: "Advanced",
    length: "10 lessons",
  },
];
